title = "Mariage de Youna & Thomas"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fr]
    title = "Mariage de Youna & Thomas"
    weight = 1
    contentDir = "content/fr"
  [languages.kr]
    title = "유나와 권영의 결혼식"
    weight = 2
    contentDir = "content/kr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Youna & Thomas"
  favicon = ""
  site_logo = ""
  description = "Site de mariage de Youna Son et Thomas Choi"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  tiktok = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "images/back.jpg"
  recent_posts_number = 2
